spring:
  datasource:
    url: jdbc:mysql://49.233.2.224/demo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-size: 100MB
server:
  port: 8080
mybatis:
  configuration:
    map-underscore-to-camel-case: true